#!/bin/sh
###
 # @Author       : wwj 318348750@qq.com
 # @Date         : 2024-04-26 15:47:53
 # @LastEditors  : wwj 318348750@qq.com
 # @LastEditTime : 2024-04-26 15:48:17
 # @Description  :
 #
 # Copyright (c) 2024 by sjft email: 318348750@qq.com, All Rights Reserved.
###

. "$(dirname "$0")/_/husky.sh"

# pnpm commitlint --edit $1
npx --no-install commitlint --edit $1
